<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE vitrine [  <!ELEMENT vitrine (canal,oferta+,urlbusca)> <!ELEMENT oferta (nome*,loja,preco*,urlimagem*,urldestino*)> <!ELEMENT canal (#PCDATA)> <!ELEMENT urlbusca (#PCDATA)> <!ELEMENT nome (#PCDATA)> <!ELEMENT loja (#PCDATA)> <!ELEMENT preco (#PCDATA)> <!ELEMENT urlimagem (#PCDATA)> <!ELEMENT urldestino (#PCDATA)> <!ELEMENT id (#PCDATA)>  <!ATTLIST oferta id CDATA "0">  ]><vitrine><canal>Globo.com</canal><urlbusca></urlbusca><oferta id="0"><nome>Brit&#226;nia El&#233;trica</nome><loja>Carrefour</loja><preco>2 x R$49,50</preco><urlimagem>http://thumbs.buscape.com.br/cafeteira/britania-cp30-eletrica_200x200-PU60450_1.jpg</urlimagem><urldestino>http://www.buscape.com.br/tr_rds?o=Z2UrOg1uZTZnNC0YCRsNNjELZhk4CAovMwo3aTlzc2VsZ2tsZ25sZmVvaG1lbmU2KiouLWRxcSosPz01OyxwLjswLTs8NzlwPTEzcDwscS4_OTthKywyYzYqKi4te20_e2w4e2w4KSkpcD0_LCw7ODErLHA9MTNwPCx7bDgdPzg7Kjs3LD9zGzI7Kiw3PT9zHCw3Kj8wNz9zDiw7KjFzHQ5tbnNvb24Ie2w4LntsOGdubmhrZ297bTg9LDg7Ki4BLDEue206PTEzLntsaD0sODsqLgE7OnttOjwrLT0_Ljt7bGg9LDg7Ki4BKiwze206PS4_e2xoKjUNMSssPTt7bTo8Ky09Py47e2xoKjURODg7LHttOmlpZjxuPDs9c2k_bWxzajpqZ3M8ODpuc2w8bjg9a2tmbz1ubntsaDoSMTl7bTpsbm9mbm1sam5ub21sangrKjMBLTErLD07YzwrLT0_Ljt4KyozATM7OjcrM2M8Ky09Py47eCsqMwE9PzMuPzc5MGM8Ky09Py47ZTAxLDs4ZW9lHAxlZWVuZW5lbmVuZWVva2xsbWlnb2lqbWduZWVvaWlwaW9wb2drcGdvZW5lMCsyMmVqbWdla29ub25lb2xvZW1nam1sbmVsampqbWpvb2hlbnBsbWVucG5lb2VlbmVuZW4-</urldestino></oferta><oferta id="0"><nome>Black &amp; Decker Ciclone A4A</nome><loja>Carrefour</loja><preco>5 x R$53,98</preco><urlimagem>http://thumbs.buscape.com.br/aspirador-de-po-agua/black-decker-ciclone-a4a-1400-w_200x200-PU93479_1.jpg</urlimagem><urldestino>http://www.buscape.com.br/tr_rds?o=Z2UfMRgtZQQdKD01G2oyPxg0KA8fFGwJMR8xOx9zc2VsZ2tsZ25sZmVvaG1lbmU2KiouLWRxcSosPz01OyxwLjswLTs8NzlwPTEzcDwscS4_OTthKywyYzYqKi4te20_e2w4e2w4KSkpcD0_LCw7ODErLHA9MTNwPCx7bDgfLS43LD86MSxzDjFzHDI_PTVzGjs9NTssc29qbm4Jcx8kKzJzH2pzHGxzbGxuCHtsOC57bDhrb2pvbG9qe204PSw4OyouASwxLnttOj0xMy57bGg9LDg7Ki4BOzp7bTo8Ky09Py47e2xoPSw4OyouASosM3ttOj0uP3tsaCo1DTErLD07e206PCstPT8uO3tsaCo1ETg4Oyx7bTo4Z2dnam9oOnNpPWw8c2o9bW5zZmhvP3M7bzhtPDs_Pz1qP257bGg6EjE5e206bG5vZm5vbGtubm9qamp4KyozAS0xKyw9O2M8Ky09Py47eCsqMwEzOzo3KzNjPCstPT8uO3grKjMBPT8zLj83OTBjPCstPT8uO2UwMSw7OGVvZRwMZWVlbmVuZW5lbmVlb2tsbG1pZ29pam1nbmVlb2lpcGlvcG9na3Bnb2VuZTArMjJlam1nZWtvbm9uZW9vZ2Vobm1sa2llbGtvZ21pbmpmZW5wbG1lbnBuZWxlZW5lbmVu</urldestino></oferta><oferta id="0"><nome>Lava Lou&#231;as Philco PH12S</nome><loja>Magazine Luiza</loja><preco>10 x R$189,99</preco><urlimagem>http://thumbs.buscape.com.br/lava-loucas/philco-ph12s-de-piso_200x200-PU95689_1.jpg</urlimagem><urldestino>http://www.buscape.com.br/tr_rds?o=Z2U3CzsbZTgnCghtBi0tHBw0PCAOKy0nDCcEOilzc2VsZ2tsZ25sZmVvaG1lbmU2KiouLWRxcSosPz01OyxwLjswLTs8NzlwPTEzcDwscS4_OTthKywyYzYqKi4te20_e2w4e2w4KSkpcDM_OT8kNzA7Mis3JD9wPTEzcDwse2w4Mj8oP3MyMSs9Py1zLjY3Mj0xcy42b2wtc29scy07LCg3PTEte2w4LntsOGxva21obWl7bDg7OntsODI_MjF7bDh7bTguPywqMDssATc6e206b25qbGl7bGgrKjMBLTErLD07e206PCstPT8uO3tsaCsqMwEzOzo3KzN7bTo9MTMuPyw_OjEsOy17bGgrKjMBPTEwKjswKnttOjs6e2xoKyozAT0_My4_Nzkwe206PCstKntsaCo1DTErLD07e206PCstPT8uO3tsaCo1ETg4Oyx7bTo8OmxsbG9mPXM8Zz1vc2poOGpzPGw4b3NtPDs4Z2pua28_a2d7bGg6EjE5e206bG5vZm5tbGpubmtqb2llMDEsOzhlb2UcDGVlZW5lbmVuZW5lZW9rbGxtaWdvaWptZ25lZW9paXBpb3BvZ2twZ29lbmUwKzIyZWptZ2VpZ2VvbGdlaG9vZ2lpZWxsb29vam1vamVucGllbnBuZW1lZW5lbmVu</urldestino></oferta><oferta id="0"><nome>Electrolux UWS10</nome><loja>Carrefour</loja><preco>10 x R$59,90</preco><urlimagem>http://thumbs.buscape.com.br/lavadora-de-alta-pressao/electrolux-uws10_200x200-PU6054b_1.jpg</urlimagem><urldestino>http://www.buscape.com.br/tr_rds?o=Z2UXNDIBZRUqay5nOTwoOSA6PTgKNTxrNw4WEA9zc2VsZ2tsZ25sZmVvaG1lbmU2KiouLWRxcSosPz01OyxwLjswLTs8NzlwPTEzcDwscS4_OTthKywyYzYqKi4te20_e2w4e2w4KSkpcD0_LCw7ODErLHA9MTNwPCx7bDgSPyg_OjEsP3M6O3MfMio_cw4sOy0tPzFzCzIqLD9zCT8tNnMLCQ1vbnNsbG4Ie2w4LntsOBMObm9nbWhubW97bTg9LDg7Ki4BLDEue206PTEzLntsaD0sODsqLgE7OnttOjwrLT0_Ljt7bGg9LDg7Ki4BKiwze206PS4_e2xoKjUNMSssPTt7bTo8Ky09Py47e2xoKjURODg7LHttOm1mbjpvbD1mcztnbGxzajprZ3Nnamdpc29sa2w8aWs8P2dobXtsaDoSMTl7bTpsbm9mbm1sam5ub2xvaHgrKjMBLTErLD07YzwrLT0_Ljt4KyozATM7OjcrM2M8Ky09Py47eCsqMwE9PzMuPzc5MGM8Ky09Py47ZTAxLDs4ZW9lHAxlZWVuZW5lbmVuZWVva2xsbWlnb2lqbWduZWVvaWlwaW9wb2drcGdvZW5lMCsyMmVqbWdla29ub25lbGpsbWVtZ2praW9lbGtuaG1paGhvZW5wbW9lbnBuZWplZW5lbmVu</urldestino></oferta><oferta id="0"><nome>Consul COA84BR Prata</nome><loja>Magazine Luiza</loja><preco>10 x R$129,90</preco><urlimagem>http://thumbs.buscape.com.br/forno-a-gas/consul-coa84br-prata_200x200-PU9b8fc_1.jpg</urlimagem><urldestino>http://www.buscape.com.br/tr_rds?o=Z2UNJxMqZTgQHG4_MTU8KjYPMRlpJhAQEDFqDilzc2VsZ2tsZ25sZmVvaG1lbmU2KiouLWRxcSosPz01OyxwLjswLTs8NzlwPTEzcDwscS4_OTthKywyYzYqKi4te20_e2w4e2w4KSkpcDM_OT8kNzA7Mis3JD9wPTEzcDwse2w4ODEsMDFzOjtzOzM8Kyo3LHM_czk_LXM9MTAtKzJzPTE_Zmo8LCwwP3NpZjJzOSw3MjJzKjczOyx7bDgue2w4bm9uZ2tvaXtsODs6e2w4OzgsO3tsOHttOC4_LCowOywBNzp7bTpvbmpsaXtsaCsqMwEtMSssPTt7bTo8Ky09Py47e2xoKyozATM7OjcrM3ttOj0xMy4_LD86MSw7LXtsaCsqMwE9MTAqOzAqe206Ozp7bGgrKjMBPT8zLj83OTB7bTo8Ky0qe2xoKjUNMSssPTt7bTo8Ky09Py47e2xoKjURODg7LHttOjxqbjhtO2k7czpoaG5zaj04O3NmZmhoc29nP2xnPWppaj9tP3tsaDoSMTl7bTpsbm9mbm1sam5ubWxsbWUwMSw7OGVvZRwMZWVlbmVuZW5lbmVlb2tsbG1pZ29pam1nbmVlb2lpcGlvcG9na3Bnb2VuZTArMjJlam1nZWlnZWdramplaG1pb2ZuZWxsZ21pbmhtbWVucGllbnBuZWtlZW5lbmVu</urldestino></oferta></vitrine>

<!--Pagina Concluida -->