<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE vitrine [  <!ELEMENT vitrine (canal,oferta+,urlbusca)> <!ELEMENT oferta (nome*,loja,preco*,urlimagem*,urldestino*)> <!ELEMENT canal (#PCDATA)> <!ELEMENT urlbusca (#PCDATA)> <!ELEMENT nome (#PCDATA)> <!ELEMENT loja (#PCDATA)> <!ELEMENT preco (#PCDATA)> <!ELEMENT urlimagem (#PCDATA)> <!ELEMENT urldestino (#PCDATA)> <!ELEMENT id (#PCDATA)>  <!ATTLIST oferta id CDATA "0">  ]><vitrine><canal>Globo.com</canal><urlbusca></urlbusca><oferta id="0"><nome>Monitor AOC E1670SW 15.6 poleg...</nome><loja>Alfatec Inform&#225;tica</loja><preco>&#224; vista R$440,00</preco><urlimagem>http://thumbs.buscape.com.br/monitor/aoc-e1670sw-led-15-6-polegadas_200x200-PU82568_1.jpg</urlimagem><urldestino>http://www.buscape.com.br/tr_rds?o=Z2UrZjA2ZW9mARs2LwFtDRVnCS8HaD8xNj84Ow9zc2VsZ2tsZ25sZ2VvaG1lbmU2KiouZHFxKSkpcD8yOD8qOz0tKjEsO3A9MTNwPCxxMzEwNyoxLHEzMTA3KjEsczI7OnNva3Nocz8xPXM7b2hpbi0pK3NvbWhocyZzaWhmczY6cyk3OjstPSw7OzBhLj8sPTs3LDFjZ25obngrKjMBLTErLD07YzwrLT0_Ljt4KyozATM7OjcrM2M8Ky09Py47eCsqMwE9PzMuPzc5MGM8Ky09Py47ZTAxLDs4ZW9lHAxlZWVuZW5lbmVuZWVva2xrZmZuampqb2hsZWVvaWlwaW9wb2dscGxsa2VuZTArMjJlam1nZW9vbWZtb29lbWhla21tZmhqZWxsbm9ob2xtb2VucGhoZW5wbmVvZWVuZW5lbg--</urldestino></oferta><oferta id="0"><nome>C&#226;mera Digital Panasonic Lumix...</nome><loja>Emania</loja><preco>&#224; vista R$8.179,04</preco><urlimagem>http://thumbs.buscape.com.br/camera-digital/panasonic-lumix-dmc-gh4-16-1-megapixels_200x200-PU8d3af_1.jpg</urlimagem><urldestino>http://www.buscape.com.br/tr_rds?o=Z2UuEzwkZTA1FBQcMCxuPxNsbW84OicuaRYnGh9zc2VsZ2tsZ25sZ2VvaG1lbmU2KiouZHFxKSkpcDszPzA3P3A9MTNwPCxxLj8wPy0xMDc9czIrMzcmczozPXM5NmpxLmErKjMBLTErLD07YzwrLT0_Ljt4KyozAS0xKyw9O2M8Ky09Py47eCsqMwEzOzo3KzNjMjcwNXgrKjMBPT8zLj83OTBjPTEzLj8sPzoxLGUwMSw7OGVvZRwMZWVlbmVuZW5lbmVlb2tsa2Zmbmpqam9obGVlb2lpcGlvcG9nbHBsbGtlbmUwKzIyZWptZ2Vvb25pbWhvZWdtZWtpZmppZ2Vsb21uZ2dob2llbnBuZW5wbmVsZWVuZW5lbg--</urldestino></oferta><oferta id="0"><nome>Tablet Multilaser Disney Vinga...</nome><loja>Dika de Presentes</loja><preco>8 x R$56,24</preco><urlimagem>http://thumbs.buscape.com.br/tablet/multilaser-disney-vingadores-wi-fi-8-gb_200x200-PU98d3f_1.jpg</urlimagem><urldestino>http://www.buscape.com.br/tr_rds?o=Z2U2FzMnZThqayQMFjwrbBYpGW1qNSxqJyQOEA9zc2VsZ2tsZ25sZ2VvaG1lbmU2KiouZHFxOjc1Pzo7Liw7LTswKjstcD0xMzM7LD07LSs3KjtwPTEzcDwscTcwODEsMz8qNz0_cSo_PDI7KnEqPzwyOypzMysyKjcyPy07LHM6Ny0wOydzKDcwOT86MSw7LXNmOTxzaXMpN3M4N3M_MDosMTc6cy8rPzpzPTEsO3M9PzNzbDMuczgsMTAqPzJhLj8sPTs3LDFjb2UwMSw7OGVvZRwMZWVlbmVuZW5lbmVlb2tsa2Zmbmpqam9obGVlb2lpcGlvcG9nbHBsbGtlbmUwKzIyZWptZ2Vvb2hubmtqZW9ubG1sZWhsa2dmbWVsamhuZmdoZ25lbnBoaGVucG5lbWVlbmVuZW4-</urldestino></oferta><oferta id="0"><nome>Vaio Fit 15S VJF155F11X Notebo...</nome><loja>VAIO Brasil</loja><preco>10 x R$289,90</preco><urlimagem>http://thumbs.buscape.com.br/notebook/vaio-fit-15s-vjf155f11x-intel-core-i5-7200u-2-5-ghz-8192-mb-1024-gb_200x200-PU9a0aa_1.jpg</urlimagem><urldestino>http://www.buscape.com.br/tr_rds?o=Z2UTahxnZTgyBhsHZi4KKSc8DhQoKAoKFQ0uPB9zc2VsZ2tsZ25sZ2VvaG1lbmU2KiouLWRxcSosPz01OyxscD86ayosPz01cD0xM3EqLD89NTsscT0yNz01YT89PWNvbW87bmdoOGs8Oj9obD06aWo7ajppOmdrPG1uZ2k7a3g3Y2tmPGlvamZnOzs9bTo4PG84ZjpuZmprO3gxY2tmPzhtamxvOzs9bTo4PG84ZmdobT09P3gsOzo3LDs9KgErLDJjNioqLi17bR97bBh7bBgpKSlwPCxwKD83MXA9MTN7bBgwMSo7PDExNXMoPzcxczg3KnNva3MtczcwKjsycz0xLDtzN2tzKTcwOjEpLXNvbnM2MTM7c2Y5PHtsGCp7bBhme2wYPT8zLj8wNj8BNzp7bBhobHttGCsqMwEtMSssPTt7bRo8Ky09Py47e2xoKyozATM7OjcrM3ttGj0uPXtsaCsqMwE9PzMuPzc5MHttGiYzMngrKjMBLTErLD07YzwrLT0_Ljt4KyozAT0_My4_NzkwYyYzMngrKjMBMzs6NyszYz0uPWUwMSw7OGVvZRwMZWVlbmVuZW5lbmVlb2tsa2Zmbmpqam9obGVlb2lpcGlvcG9nbHBsbGtlbmUwKzIyZWptZ2Vvb2tsbmdoZWhqbGplaG1uZ2tqZWxqZm9mb21rZmVvcG9sZW5wbmVqZWVuZW5lbg--</urldestino></oferta><oferta id="0"><nome>Tablet Multilaser Kid Pad Wi-F...</nome><loja>Dika de Presentes</loja><preco>8 x R$56,13</preco><urlimagem>http://thumbs.buscape.com.br/tablet/multilaser-kid-pad-wi-fi-8-gb_200x200-PU954d4_1.jpg</urlimagem><urldestino>http://www.buscape.com.br/tr_rds?o=Z2UEJ2wZZSgYLzMnbWYyLxM5MhQmKSs6DAQBPR9zc2VsZ2tsZ25sZ2VvaG1lbmU2KiouZHFxOjc1Pzo7Liw7LTswKjstcD0xMzM7LD07LSs3KjtwPTEzcDwscSo_PDI7KnMzKzIqNzI_LTssczU3OnMuPzpzZjk8cy8rPzo9MSw7cz8wOiwxNzpqc2pzPyQrMnMwPG9namEuPyw9OzcsMWNvZTAxLDs4ZW9lHAxlZWVuZW5lbmVuZWVva2xrZmZuampqb2hsZWVvaWlwaW9wb2dscGxsa2VuZTArMjJlam1nZW9vaG5ua2plb25sbWxlaG9va2puZWxqaG5mZ2hmaWVucGhoZW5wbmVrZWVuZW5lbg--</urldestino></oferta></vitrine>

<!--Pagina Concluida -->