<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vitrine [  <!ELEMENT vitrine (canal,oferta+,urlbusca)> <!ELEMENT oferta (nome*,loja,preco*,urlimagem*,urldestino*)> <!ELEMENT canal (#PCDATA)> <!ELEMENT urlbusca (#PCDATA)> <!ELEMENT nome (#PCDATA)> <!ELEMENT loja (#PCDATA)> <!ELEMENT preco (#PCDATA)> <!ELEMENT urlimagem (#PCDATA)> <!ELEMENT urldestino (#PCDATA)> <!ELEMENT id (#PCDATA)>  <!ATTLIST oferta id CDATA "0">  ]>
<vitrine>
    <canal>Globo.com</canal>
    <urlbusca></urlbusca>
    <oferta id="0">
        <nome>Console Playstation 4 PS4</nome>
        <loja>Walmart</loja>
        <preco>à vista R$1.699,00</preco>
        <urlimagem>https://static.wmobjects.com.br/imgres/arquivos/ids/10862219-1000-1000/console-playstation-4-ps4-slim-1tb---1-controle-dualshock-4.jpg</urlimagem>
        <urldestino>https://www.walmart.com.br/console-playstation-4-ps4-slim-1tb-1-controle-dualshock-4/5264953/pr</urldestino>
    </oferta>
    <oferta id="0">
        <nome>Notebook Gamer Acer Nitro 5 AN515-51-75KZ</nome>
        <loja>Walmart</loja>
        <preco>12x de R$ 394,92</preco>
        <urlimagem>//static.wmobjects.com.br/imgres/arquivos/ids/14597494-344-344/notebook-gamer-acer-nitro-5-an515-51-75kz-intel-core-i7-16gb-ram-1tb-hd-tela-ips-full-hd-15-6--nvidia-geforce-gtx-1050-ti-4gb-windows-10.jpg</urlimagem>
        <urldestino>https://www.walmart.com.br/notebook-gamer-acer-nitro-5-an515-51-75kz-intel-core-i7-16gb-ram-1tb-hd-tela-ips-full-hd-15-6-nvidia-geforce-gtx-1050-ti-4gb-windows-10/6638269/pr</urldestino>
    </oferta>
    <oferta id="0">
        <nome>Iphone X 64GB Tela 5.8 IOS 11 4G Wi-Fi</nome>
        <loja>Walmart</loja>
        <preco>à vista R$4.879,00</preco>
        <urlimagem>https://static.wmobjects.com.br/imgres/arquivos/ids/14096195-1000-1000/iphone-x-64gb-tela-5-8-ios-11-4g-wi-fi-camera-12mp-apple.jpg</urlimagem>
        <urldestino>https://www.walmart.com.br/iphone-x-64gb-tela-5-8-ios-11-4g-wi-fi-camera-12mp-apple/6455038/pr</urldestino>
    </oferta>
    <oferta id="0">
        <nome>Samsung S8+ Plus SM-G955 64GB</nome>
        <loja>Walmart</loja>
        <preco>à vista R$4.399,00</preco>
        <urlimagem>http://thumbs.buscape.com.br/celular-e-smartphone/smartphone-samsung-galaxy-s8-plus-sm-g955-64gb_200x200-PU9a487_1.jpg</urlimagem>
        <urldestino>http://www.buscape.com.br/tr_rds?o=Z2UXZgRuZSdnbzRpEjIabBdoMiwwJhocHChtOjlzc2VsZ2tsZ25tbGVvaG1lbmU2KiouLWRxcSkpKXAsNz89Nis7MjFwPTEzcDwscS0zPywqLjYxMDtzLT8zLSswOXM5PzI_JidzLWZzLjIrLXM6Kz8ycz02Ny5zPzA6LDE3OnNpc25zKjsyP3Noc2xzaGo5PHM9PzM7LD9zb2wzLnMuLD8qOz86MXNvb2lpa2xubWErKjMBLTErLD07YzwrLT0_Ljt4KyozATM7OjcrM2M9MTMuPyw_OjEsZTAxLDs4ZW9lHAxlZWVuZW5lbmVuZWVva2xsam1rZ2hqbm9mZWVvaWlwaW9wb2dscGxsa2VuZTArMjJlam1nZWlrbW5pbmVpaWVobW9nam1lbGtob2ZmZm5vZW5waGVucG5lbWVlbmVuZW4-</urldestino>
    </oferta>
    <oferta id="0">
        <nome>TV LED 32' LG HD 1 HDMI 1 USB Conversor Digital</nome>
        <loja>Walmart</loja>
        <preco>10x de R$84,90</preco>
        <urlimagem>https://static.wmobjects.com.br/imgres/arquivos/ids/9767181-1000-1000/tv-led-32--lg-hd-1-hdmi-1-usb-conversor-digital-32lw300c.jpg</urlimagem>
        <urldestino>https://www.walmart.com.br/tv-led-32-lg-hd-1-hdmi-1-usb-conversor-digital-32lw300c/4787176/pr</urldestino>
    </oferta>
</vitrine>
<!--Pagina Concluida -->
